import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tuitah</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main>
        <header>
          <h1>Tuitah</h1>
        </header>
      </main>
    </>
  );
}
